### ISSUE TITLE
Playable Missions Tracker

### ISSUE THREAD

**Issue by tsjost** [rwengine/openrw#52]
# Story Missions

### 8-Ball
- [ ] Give Me Liberty

### Luigi
- [ ] Luigi's Girls
- [ ] Don't Spank Ma Bitch Up
- [ ] Drive Misty For Me
- [ ] Pump-Action Pimp
- [ ] The Fuzz Ball

### Joey
- [ ] Mike Lips Last Lunch
- [ ] Farewell 'Chunky' Lee Chong
- [ ] Van Heist
- [ ] Cipriani's Chauffeur
- [ ] Dead Skunk in the Trunk (optional)
- [ ] The Getaway (optional)

### Toni
- [ ] Taking Out The Laundry
- [ ] The Pick-Up
- [ ] Salvatore's Called A Meeting

### Salvatore
- [ ] Chaperone

### Toni
- [ ] Triads and Tribulations
- [ ] Blow Fish

### Salvatore
- [ ] Cutting The Grass
- [ ] Bomb Da Base: Act I

### 8-Ball
- [ ] Bomb Da Base: Act II

### Salvatore
- [ ] Last Requests

### Asuka
- [ ] Sayonara Salvatore
- [ ] Under Surveillance
- [ ] Paparazzi Purge
- [ ] Payday For Ray
- [ ] Two-Faced Tanner

### Kenji
- [ ] Kanbu Bust-out
- [ ] Grand Theft Auto
- [ ] Deal Steal
- [ ] Shima
- [ ] Smack Down

### Ray
- [ ] Silence The Sneak
- [ ] Arms Shortage
- [ ] Evidence Dash
- [ ] Gone Fishing
- [ ] Plaster Blaster

### Donald
- [ ] Liberator
- [ ] Waka-Gashira Wipeout
- [ ] A Drop In The Ocean
- [ ] Grand Theft Aero
- [ ] Escort Service
- [ ] Decoy
- [ ] Love's Disappearance

### Ray
- [ ] Marked Man

### Asuka
- [ ] Bait
- [ ] Espresso-2-Go!
- [ ] S.A.M.

### Catalina
- [ ] Ransom

### Catalina
- [ ] The Exchange

**Comment by JayFoxRox** [comment]
# Phone missions

## Portland

### El Burro
- [ ] Turismo: Win a street race.
- [ ] I Scream, You Scream: Arm an ice cream truck with a bomb and blow up a group of gang members.
- [ ] Trial By Fire: Burn twenty-five Triads in two minutes.
- [ ] Big 'N Veiny: Pick up some magazines and take them to XXXMags in Red Light District

### Marty Chonks
- [ ] The Crook: Bring a bank manager to the dog food factory and crush the evidence.
- [ ] The Thieves: Bring two thieves to the food factory and respray Marty's car.
- [ ] The Wife: Bring Marty's wife to the food factory and and dump the car into the sea.
- [ ] Her Lover: Bring Carl to the food factory.

## Staunton Island

### King Courtney
- [ ] Bling-Bling Scramble: Win a checkpoint race.
- [ ] Uzi Rider: Kill ten Diablo gang members.
- [ ] Gangcar Round-Up: Bring three gang cars to a garage in Newport.
- [ ] Kingdom Come: Destroy some SPANKed up madmen vans and reveal the betrayal of King Courtney.

## Shoreside Vale

### D-Ice
- [ ] Uzi Money: Drive-by 25 Purple Nines in two minutes.
- [ ] Toyminator: Destroy three gang cars with an RC Bandit.
- [ ] Rigged to Blow: Bring an armed car to a garage before it explodes.
- [ ] Bullion Run: Pick up as many pieces of bullion as possible and take them to a garage.
- [ ] Rumble: Kill as many Purple Nines as possible using only melee weapons.

**Comment by JayFoxRox** [comment]
# Side Missions

## Off-Road missions

- [ ] Patriot Playground
- [ ] A Ride in the Park
- [ ] Multistorey Mayhem
- [ ] Gripped!

## Remote controlled vehicle missions

- [ ] Diablo Destruction
- [ ] Mafia Massacre
- [ ] Casino Calamity
- [ ] Rumpo Rampage

## Vehicle missions

- [ ] Taxi Driver
- [ ] Vigilante
- [ ] Fire Truck
- [ ] Ambulance

## Import / Export missions

- [ ] Portland Island Emergency Vehicle Crane
- [ ] Portland Island Garage
- [ ] Shoreside Vale Garage

## Miscellaneous

- [ ] All 20 Unique Jumps
- [ ] All 20 Rampage missions
- [ ] All 100 Hidden packages

**Comment by hazelnot** [comment]
Don't Spank Ma Bitch Up is marked as playable, but I'm unable to complete it because of the garage at the end.

**Comment by tsjost** [comment]
@hazelnot Press _M_ to open the ingame debug menu, go into _Map_ and select _Unsolid garage doors_ :)

**Comment by husho** [comment]
Paramedic should be playable after #443 merge, vigilante is sorta playable too.
Cipriani's Chauffeur should not longer crash after #437 merge.

**Comment by husho** [comment]
Hospital, police info cutscenes (these are missions) and hidden packages work with #449 
Police one crashes in opcode_01ad, but that should be fixed in #448
Taking Out The Laundry #448 
The Pick-Up #449  
Triads and Tribulations should no longer crash with #437

**Comment by ShFil119** [comment]
Shouldn't it be moved to wiki?

**Comment by dracc** [comment]
I agree with @shfil.

**Comment by Matriks404** [comment]
I would love to see a list of stuff that is unimplemented/wrong for each mission, it would be best in a Wiki page I guess...

**Comment by Spike1377** [comment]
> @hazelnot Press _M_ to open the ingame debug menu, go into _Map_ and select _Unsolid garage doors_ :)

if you gotta use debug menu, dose it really count as playable, the door should just open by itself.

**Comment by hazelnot** [comment]
The project is pretty much dead as far as I can tell, hasn't been updated in almost 2 years lol

**Comment by Spike1377** [comment]
welp thats sad.

**Comment by recore67** [comment]
revival anytime soon?
