### ISSUE TITLE
Playable Missions Tracker

### ISSUE THREAD

**Issue by tsjost** [rwengine/openrw#53]
# Story Missions

### 8-Ball

- [ ] Give Me Liberty

### Luigi

- [ ] Luigi's Girls
- [ ] Don't Spank Ma Bitch Up
- [ ] Drive Misty For Me
- [ ] Pump-Action Pimp
- [ ] The Fuzz Ball

### Joey

- [ ] Mike Lips Last Lunch
- [ ] Farewell 'Chunky' Lee Chong
- [ ] Van Heist
- [ ] Cipriani's Chauffeur
- [ ] Dead Skunk in the Trunk
- [ ] The Getaway

### Toni

- [ ] Taking Out The Laundry
- [ ] The Pick-Up
- [ ] Salvatore's Called A Meeting

### Salvatore

- [ ] Chaperone

### Toni

- [ ] Triads and Tribulations
- [ ] Blow Fish

### Salvatore

- [ ] Cutting The Grass
- [ ] Bomb Da Base

### 8-Ball

- [ ] Bomb Da Base

### Salvatore

- [ ] Last Requests

### Asuka

- [ ] Sayonara Salvatore
- [ ] Under Surveillance
- [ ] Paparazzi Purge
- [ ] Payday For Ray
- [ ] Two-Faced Tanner

### Kenji

- [ ] Kanbu Bust-out
- [ ] Grand Theft Auto
- [ ] Deal Steal
- [ ] Shima
- [ ] Smack Down

### Ray

- [ ] Silence The Sneak
- [ ] Arms Shortage
- [ ] Evidence Dash
- [ ] Gone Fishing
- [ ] Plaster Blaster

### Donald

- [ ] Liberator
- [ ] Waka-Gashira Wipeout
- [ ] A Drop In The Ocean
- [ ] Grand Theft Aero
- [ ] Escort Service
- [ ] Decoy
- [ ] Love's Disappearance

### Ray

- [ ] Marked Man

### Asuka

- [ ] Bait
- [ ] Espresso-2-Go!
- [ ] S.A.M.

### Catalina

- [ ] Ransom

### Catalina

- [ ] The Exchange
