### ISSUE TITLE
State of implementing sfx sounds

### ISSUE THREAD

**Issue by ghost** [rwengine/openrw#581]
List of tasks:
- [x] loader for sfx #112 
- [x] loading and decoding via FFmpeg #522 
- [x] logic to manage sfx #558
- [x] Sound as script object 1b1b924d8fa4f1550a6734eaea3230657c8dc84c
- [x] 018c 1769830af06e2f8bee9ec6e1a5e98b2a534cad38
- [x] 018d 048839e00019446afdad8fdd0c0e6cba33ad4bfb
- [x] 018e 7b8e7a4e9fdc5e0ae82b4be8ae5be778bad271df
- [x] 03d7 a8bdc83b0ef3955ff3dd50a1608de9c4476c905d
- [x] implementing hardcoded data about sfx metadata 4119afbae36f79c30fb59a35e24ee0eb37f367d3
- [x] grabbing position of camera 746b8f7d20b0f879199847ec5e2a5c753a885c15 cb69ad596eb408c9a054798163534dceeb49732f
- [ ] velocity of listener
- [ ] RE objects logic of generating sounds
- [ ] some continuous sounds have break time (and how long?)

Last time of editing: 15.08.18.

For additional tasks/requests please comment. ;)
